all:
	gcc -std=gnu99 -c main.c
	gcc -std=gnu99 -c menu_display.c
	gcc -std=gnu99 -c password.c
	gcc -std=gnu99 -c check_pass.c
	gcc -std=gnu99 -c student.c
	gcc -std=gnu99 -c teacher.c
	gcc -std=gnu99 -c stuinfo.c
	gcc -std=gnu99 -c stuscore.c
	gcc -std=gnu99 -c admin_menu.c
	gcc -std=gnu99 -c fuzhu.c
	gcc -std=gnu99 -c hanshu.c
	gcc -std=gnu99 -c hanshu1.c
	gcc -std=gnu99 -c super_admin.c
	gcc -std=gnu99 -c rank.c
	gcc main.o menu_display.o password.o check_pass.o student.o teacher.o stuinfo.o stuscore.o admin_menu.o fuzhu.o hanshu.o hanshu1.o super_admin.o rank.c -o 123
